// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./pages/api/joke.ts";
import * as $1 from "./pages/[name].tsx";
import * as $2 from "./pages/_render.ts";
import * as $3 from "./pages/notfound.tsx";
import * as $4 from "./pages/index.tsx";

const routes = {
  pages: {
    "./pages/api/joke.ts": $0,
    "./pages/[name].tsx": $1,
    "./pages/_render.ts": $2,
    "./pages/notfound.tsx": $3,
    "./pages/index.tsx": $4,
  },
  baseUrl: import.meta.url,
};

export default routes;
